### ISSUE TITLE
amq-html-demo: does not run on OpenShift 4

### ISSUE THREAD

**Issue by rbaumgar** [hguerrero/amq-examples#7]
Hugo,
nodejs:6 is not available on OpenShift 4.
if I update to nodejs:8 or nodejs:10
```
> amq-html-demo@1.0.0 start /opt/app-root/src 
> gulp serve 
sh: gulp: command not found 
npm info lifecycle amq-html-demo@1.0.0~start: Failed to exec start script
```
should be updated to gulp 4...

kr Robert

**Comment by hguerrero** [comment]
Fixed:

- Updated the nodejs image to nodejs:10
- Fixed the dependencies for gulp as those were devDependencies and we are using gulp not only to build but also to serve.
- Changed the replacement of the env variables to the js code instead of the old html ones.

Should be working now.
